# Generated by Django 2.1 on 2019-01-30 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname_text', models.CharField(max_length=100)),
                ('lastname_text', models.CharField(max_length=100)),
                ('birthdate_field', models.DateTimeField(verbose_name='Date of Birth')),
                ('platform_text', models.CharField(max_length=100)),
            ],
        ),
    ]
